export const QUESTIONS = [
  {
    id: 1,
    category: 'Postura Org. IA',
    shortLabel: '1. Postura IA',
    title: '1. Postura Organizacional sobre la IA',
    question: '¿Qué tan clara es la política de tu empresa sobre el uso de la IA?',
    options: [
      { val: 1, text: '(1) No existe política ni orientación oficial.' },
      { val: 2, text: '(2) Hay rumores de una política, pero nadie la conoce con claridad.' },
      { val: 3, text: '(3) Existe un documento, pero su aplicación es ambigua o inconsistente.' },
      { val: 4, text: '(4) La política es clara y guía la mayoría de nuestros experimentos.' },
      { val: 5, text: '(5) La postura es cristalina, comunicada y fomenta activamente la innovación segura.' },
    ],
  },
  {
    id: 2,
    category: 'Salud de Datos',
    shortLabel: '2. Salud Datos',
    title: '2. Salud del Ecosistema de Datos',
    question: '¿Cómo es la calidad y accesibilidad de tus datos internos?',
    options: [
      { val: 1, text: '(1) Los datos son de baja calidad y están totalmente aislados en silos.' },
      { val: 2, text: '(2) Los datos existen, pero acceder a ellos es un proceso lento y manual.' },
      { val: 3, text: '(3) Calidad aceptable, pero la unificación entre departamentos es inconsistente.' },
      { val: 4, text: '(4) Datos de alta calidad, unificados y fácilmente accesibles para la mayoría.' },
      { val: 5, text: '(5) Ecosistema de datos excelente, unificado y listo para consumo inmediato de la IA.' },
    ],
  },
  {
    id: 3,
    category: 'Contexto IA',
    shortLabel: '3. Contexto IA',
    title: '3. Accesibilidad de Datos para la IA (Contexto)',
    question: '¿Con qué frecuencia usas datos internos de la empresa en tus prompts/agentes?',
    options: [
      { val: 1, text: '(1) Nunca; usamos la IA solo con información general de internet.' },
      { val: 2, text: '(2) Rara vez; el proceso de dar contexto interno es muy complejo.' },
      { val: 3, text: '(3) A veces; inyectamos contexto de forma manual y artesanal.' },
      { val: 4, text: '(4) Casi siempre; las herramientas están conectadas a fuentes de datos clave.' },
      { val: 5, text: '(5) Siempre; la IA opera con contexto rico y tiempo real de la organización.' },
    ],
  },
  {
    id: 4,
    category: 'Lotes Pequeños',
    shortLabel: '4. Lotes Pqs.',
    title: '4. Trabajo en Lotes Pequeños (Small Batches)',
    question: '¿Cómo se divide y entrega el trabajo asistido por IA?',
    options: [
      { val: 1, text: '(1) Entregas masivas y poco frecuentes (meses).' },
      { val: 2, text: '(2) Lotes grandes con dependencias complejas entre equipos.' },
      { val: 3, text: '(3) Entregas moderadas; algunas tareas se dividen bien, otras no.' },
      { val: 4, text: '(4) Trabajo fluido en unidades pequeñas que se completan en pocos días.' },
      { val: 5, text: '(5) Lotes mínimos; realizamos múltiples despliegues exitosos al día.' },
    ],
  },
  {
    id: 5,
    category: 'Enfoque Usuario',
    shortLabel: '5. Usuario',
    title: '5. Enfoque Centrado en el Usuario',
    question: '¿Cuál es la prioridad al desarrollar soluciones con IA?',
    options: [
      { val: 1, text: '(1) La tecnología por sí misma; no tenemos métricas de usuario.' },
      { val: 2, text: '(2) Cumplir con requerimientos técnicos internos principalmente.' },
      { val: 3, text: '(3) Equilibrio entre necesidades técnicas y feedback ocasional del usuario.' },
      { val: 4, text: '(4) La experiencia del usuario guía la mayoría de nuestras decisiones de IA.' },
      { val: 5, text: '(5) El valor para el usuario final es nuestra brújula absoluta (North Star).' },
    ],
  },
  {
    id: 6,
    category: 'Plataforma Interna',
    shortLabel: '6. Plataforma',
    title: '6. Calidad de la Plataforma Interna',
    question: '¿Tu plataforma oculta la complejidad y ofrece autoservicio?',
    options: [
      { val: 1, text: '(1) No hay plataforma; cada tarea requiere intervención manual de TI.' },
      { val: 2, text: '(2) Hay herramientas básicas, pero la fricción operativa es muy alta.' },
      { val: 3, text: '(3) Plataforma funcional, pero requiere mucho soporte para tareas complejas.' },
      { val: 4, text: '(4) Ofrece buenas funciones de autoservicio y automatización confiable.' },
      { val: 5, text: '(5) La plataforma es un multiplicador de fuerzas; autonomía total del equipo.' },
    ],
  },
  {
    id: 7,
    category: 'Resiliencia',
    shortLabel: '7. Resiliencia',
    title: '7. Control de Versiones y Resiliencia',
    question: '¿Qué tan rápido pueden revertir un cambio si la IA genera código inestable?',
    options: [
      { val: 1, text: '(1) Imposible revertir rápido; las fallas causan crisis prolongadas.' },
      { val: 2, text: '(2) Proceso de reversión lento y manual que toma horas o días.' },
      { val: 3, text: '(3) Podemos revertir, pero el proceso es estresante y poco frecuente.' },
      { val: 4, text: '(4) Prácticas sólidas; reversión rápida (rollbacks) en minutos.' },
      { val: 5, text: '(5) Resiliencia total; infraestructura inmutable y reversión automática.' },
    ],
  },
];

export const SAMPLE_NAMES = [
  'María González',
  'Carlos Rodríguez',
  'Ana Silva',
  'Diego Morales',
  'Laura Pérez',
  'Felipe Castro',
  'Sofía Gómez',
  'Javier Fernández',
  'Elena Torres',
  'Gabriel Rojas',
];